"""create poem

Revision ID: 24eb2055a4ef
Revises: 932c6dcf8439
Create Date: 2018-08-29 15:44:28.622180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24eb2055a4ef'
down_revision = '932c6dcf8439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
